# Generated by Django 6.0.8 on 2026-08-31 10:23

import django.db.models.deletion
import djmoney.models.fields
import djmoney.money
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("users", "0002_invitation_alter_employee_employee_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this record has been soft-deleted.",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "application_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated unique identifier for the application.",
                        max_length=50,
                        unique=True,
                        verbose_name="Application number",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message provided by the tenant.",
                        verbose_name="Message",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current status of the rental application.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Time at which the application was submitted.",
                        verbose_name="Applied at",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time at which the application was reviewed.",
                        null=True,
                        verbose_name="Reviewed at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_rental_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant submitting the application.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_applications",
                        to="users.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="The unit being applied for.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_applications",
                        to="properties.unit",
                        verbose_name="Unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rental application",
                "verbose_name_plural": "Rental applications",
                "db_table": "rental_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RentalContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this record has been soft-deleted.",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated unique identifier for the contract.",
                        max_length=50,
                        unique=True,
                        verbose_name="Contract number",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="The date when the contract becomes effective.",
                        verbose_name="Start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave empty for an open-ended contract.",
                        null=True,
                        verbose_name="End date",
                    ),
                ),
                (
                    "monthly_rent_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("XAF", "Central African CFA Franc"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="XAF",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "monthly_rent",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default_currency="XAF",
                        help_text="Monthly rental amount in the local currency.",
                        max_digits=12,
                        verbose_name="Monthly rent",
                    ),
                ),
                (
                    "deposit_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[
                            ("XAF", "Central African CFA Franc"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="XAF",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "deposit",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=djmoney.money.Money(0, "XAF"),
                        default_currency="XAF",
                        help_text="Security deposit required at contract signing.",
                        max_digits=12,
                        verbose_name="Security deposit",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("TERMINATED", "Terminated"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        help_text="Current lifecycle status of the contract.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        blank=True,
                        help_text="Approved application that resulted in this contract.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rental_contract",
                        to="rentals.rentalapplication",
                        verbose_name="Rental application",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant who signs this contract.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_contracts",
                        to="users.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="The unit being rented under this contract.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_contracts",
                        to="properties.unit",
                        verbose_name="Unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rental contract",
                "verbose_name_plural": "Rental contracts",
                "db_table": "rental_contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="rentalapplication",
            index=models.Index(fields=["tenant"], name="rental_app_tenant_idx"),
        ),
        migrations.AddIndex(
            model_name="rentalapplication",
            index=models.Index(fields=["unit"], name="rental_app_unit_idx"),
        ),
        migrations.AddIndex(
            model_name="rentalapplication",
            index=models.Index(fields=["status"], name="rental_app_status_idx"),
        ),
        migrations.AddIndex(
            model_name="rentalapplication",
            index=models.Index(
                fields=["reviewed_at"], name="rental_app_reviewed_at_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("tenant", "unit"),
                name="unique_pending_application_per_tenant_unit",
            ),
        ),
        migrations.AddIndex(
            model_name="rentalcontract",
            index=models.Index(fields=["tenant"], name="rental_contract_tenant_idx"),
        ),
        migrations.AddIndex(
            model_name="rentalcontract",
            index=models.Index(fields=["unit"], name="rental_contract_unit_idx"),
        ),
        migrations.AddIndex(
            model_name="rentalcontract",
            index=models.Index(fields=["status"], name="rental_contract_status_idx"),
        ),
        migrations.AddIndex(
            model_name="rentalcontract",
            index=models.Index(fields=["start_date"], name="rental_contract_start_idx"),
        ),
        migrations.AddConstraint(
            model_name="rentalcontract",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("unit",),
                name="unique_active_contract_per_unit",
            ),
        ),
    ]
