# Generated by Django 6.0.8 on 2026-08-31 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('properties', '0002_models'),
        ('rentals', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rental_applications', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant submitting the application.', on_delete=django.db.models.deletion.PROTECT, related_name='rental_applications', to='users.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='unit',
            field=models.ForeignKey(help_text='The unit being applied for.', on_delete=django.db.models.deletion.PROTECT, related_name='rental_applications', to='properties.unit', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='application',
            field=models.OneToOneField(blank=True, help_text='Approved application that resulted in this contract.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_contract', to='rentals.rentalapplication', verbose_name='Rental application'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant who signs this contract.', on_delete=django.db.models.deletion.PROTECT, related_name='rental_contracts', to='users.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='unit',
            field=models.ForeignKey(help_text='The unit being rented under this contract.', on_delete=django.db.models.deletion.PROTECT, related_name='rental_contracts', to='properties.unit', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['tenant'], name='rental_app_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['unit'], name='rental_app_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['status'], name='rental_app_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['reviewed_at'], name='rental_app_reviewed_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentalapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('tenant', 'unit'), name='unique_pending_application_per_tenant_unit'),
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['tenant'], name='rental_contract_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['unit'], name='rental_contract_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['status'], name='rental_contract_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['start_date'], name='rental_contract_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentalcontract',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('unit',), name='unique_active_contract_per_unit'),
        ),
    ]
