# Generated by Django 6.0.8 on 2026-09-23 12:01

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rentalapplication',
            managers=[
                ('landlord_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rentalcontract',
            managers=[
                ('landlord_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
