# Generated by Django 6.0.8 on 2026-09-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='desired_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Desired rental duration in months.', null=True, verbose_name='Desired duration'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='desired_move_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='Desired move-in date'),
        ),
        migrations.AddField(
            model_name='rentalapplication',
            name='occupants_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of occupants'),
        ),
    ]
