# Generated by Django 6.0.8 on 2026-09-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rentalapplication_desired_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='advance_rent_months',
            field=models.PositiveIntegerField(default=1, help_text='Number of months paid in advance.', verbose_name='Advance rent (months)'),
        ),
    ]
