# Generated by Django 6.0.8 on 2026-09-25 13:45

from django.db import migrations, models
from django.utils.text import slugify
import re


UUID_PATTERN = re.compile(
    r"\b[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b",
    re.IGNORECASE,
)


def regenerate_slugs(apps, schema_editor):
    app_label = __name__.split(".")[0]
    models_with_slugs = [
        model
        for model in apps.get_app_config(app_label).get_models()
        if any(field.name == "slug" for field in model._meta.fields)
    ]
    for model in models_with_slugs:
        model._base_manager.all().update(slug=None)

    fields = (
        "name",
        "title",
        "unit_number",
        "contract_number",
        "property_number",
        "building_number",
        "application_number",
        "charge_number",
        "payment_number",
        "receipt_number",
        "request_number",
        "task_number",
        "schedule_number",
        "visit_number",
        "invitation_number",
        "announcement_number",
        "notification_number",
        "message_number",
        "landlord_number",
        "tenant_number",
        "employee_number",
        "agent_number",
        "guard_number",
        "visitor_name",
        "caption",
    )
    for model in models_with_slugs:
        used = set()
        rows = model._base_manager.order_by("created_at", "pk").iterator()
        for obj in rows:
            source = None
            if model._meta.label_lower == "users.user":
                source = " ".join(
                    part for part in (obj.first_name, obj.last_name) if part
                )
            if not source:
                source = next(
                    (getattr(obj, name) for name in fields if getattr(obj, name, None)),
                    model._meta.verbose_name,
                )
            base = slugify(UUID_PATTERN.sub("", str(source)))[:180].strip("-")
            base = base or model._meta.model_name
            slug = base
            suffix = 2
            while slug in used:
                slug = f"{base[:180]}-{suffix}"[:200]
                suffix += 1
            used.add(slug)
            obj.slug = slug[:200]
            obj.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0003_unique_open_contract_per_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalapplication",
            name="slug",
            field=models.SlugField(
                blank=True,
                editable=False,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="URL slug",
            ),
        ),
        migrations.AddField(
            model_name="rentalcontract",
            name="slug",
            field=models.SlugField(
                blank=True,
                editable=False,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="URL slug",
            ),
        ),
        migrations.RunPython(regenerate_slugs, migrations.RunPython.noop),
    ]
