# Generated by Django 6.0.8 on 2026-09-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rentalcontract_advance_rent_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontract',
            name='status',
            field=models.CharField(choices=[('SIGNING', 'Signing'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], db_index=True, default='SIGNING', help_text='Current lifecycle status of the contract.', max_length=20, verbose_name='Status'),
        ),
    ]
