# Generated by Django 6.0.8 on 2026-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_alter_rentalcontract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='landlord_signature',
            field=models.ImageField(blank=True, help_text='Digital signature of the landlord (SVG, base64 PNG, or hash).', null=True, upload_to='contracts/signatures/', verbose_name='Landlord signature'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='landlord_signed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the landlord signed the contract.', null=True, verbose_name='Landlord signed at'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='tenant_signature',
            field=models.ImageField(blank=True, help_text='Digital signature of the tenant (SVG, base64 PNG, or hash).', null=True, upload_to='contracts/signatures/', verbose_name='Tenant signature'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='tenant_signed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the tenant signed the contract.', null=True, verbose_name='Tenant signed at'),
        ),
    ]
