# Generated by Django 6.0.8 on 2026-09-25 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_named_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcontract',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Terminated at'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='terminated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminated_rental_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Terminated by'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='termination_reason',
            field=models.TextField(blank=True, verbose_name='Termination reason'),
        ),
    ]
