# Generated by Django 6.0.8 on 2026-09-18 17:15

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_rentalcontract_landlord_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontract',
            name='landlord_signature',
            field=models.ImageField(blank=True, help_text='Digital signature of the landlord (SVG, base64 PNG, or hash).', null=True, upload_to='contracts/signatures/', validators=[core.validators.validate_signature], verbose_name='Landlord signature'),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='tenant_signature',
            field=models.ImageField(blank=True, help_text='Digital signature of the tenant (SVG, base64 PNG, or hash).', null=True, upload_to='contracts/signatures/', validators=[core.validators.validate_signature], verbose_name='Tenant signature'),
        ),
    ]
