# Generated by Django 6.0.8 on 2026-09-25 20:47

import django.db.models.deletion
import djmoney.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_rentalcontract_terminated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractExtensionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True, verbose_name='URL slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('requested_end_date', models.DateField(verbose_name='Requested end date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved, awaiting payment'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_amount_currency', djmoney.models.fields.CurrencyField(choices=[('XAF', 'Central African CFA Franc'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='XAF', editable=False, max_length=3, null=True)),
                ('approved_amount', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='XAF', max_digits=12, null=True, verbose_name='Approved extension amount')),
                ('payment_charge_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extension_requests', to='rentals.rentalcontract', verbose_name='Rental contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contract_extensions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('contract',), name='one_pending_extension_per_contract')],
            },
        ),
    ]
