# Generated by Django 6.0.8 on 2026-08-31 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("users", "0002_invitation_alter_employee_employee_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CleaningSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this record has been soft-deleted.",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "schedule_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated unique identifier for the cleaning schedule.",
                        max_length=50,
                        unique=True,
                        verbose_name="Schedule number",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        help_text="The date when the cleaning is scheduled.",
                        verbose_name="Scheduled date",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="The time the cleaning is scheduled to start.",
                        null=True,
                        verbose_name="Start time",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True,
                        help_text="The time the cleaning is scheduled to end.",
                        null=True,
                        verbose_name="End time",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional details about the cleaning task.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        help_text="Current status of the cleaning schedule.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "assigned_employees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="cleaning_schedules",
                        to="users.employee",
                        verbose_name="Assigned employees",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        help_text="The building to be cleaned.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cleaning_schedules",
                        to="properties.building",
                        verbose_name="Building",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cleaning schedule",
                "verbose_name_plural": "Cleaning schedules",
                "db_table": "cleaning_schedules",
                "ordering": ["scheduled_date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["building"], name="cleaning_schedule_building_idx"
                    ),
                    models.Index(
                        fields=["scheduled_date"], name="cleaning_schedule_date_idx"
                    ),
                    models.Index(
                        fields=["status"], name="cleaning_schedule_status_idx"
                    ),
                    models.Index(
                        fields=["building", "scheduled_date"],
                        name="cleaning_building_date_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "SCHEDULED")),
                        fields=("building", "scheduled_date"),
                        name="unique_scheduled_cleaning_per_building_date",
                    )
                ],
            },
        ),
    ]
