# Generated by Django 6.0.8 on 2026-08-31 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('schedule_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the cleaning schedule.', max_length=50, unique=True, verbose_name='Schedule number')),
                ('scheduled_date', models.DateField(help_text='The date when the cleaning is scheduled.', verbose_name='Scheduled date')),
                ('start_time', models.TimeField(blank=True, help_text='The time the cleaning is scheduled to start.', null=True, verbose_name='Start time')),
                ('end_time', models.TimeField(blank=True, help_text='The time the cleaning is scheduled to end.', null=True, verbose_name='End time')),
                ('description', models.TextField(blank=True, help_text='Optional details about the cleaning task.', verbose_name='Description')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', help_text='Current status of the cleaning schedule.', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Cleaning schedule',
                'verbose_name_plural': 'Cleaning schedules',
                'db_table': 'cleaning_schedules',
                'ordering': ['scheduled_date', 'start_time'],
            },
        ),
    ]
