# Generated by Django 6.0.8 on 2026-08-31 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('properties', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningschedule',
            name='assigned_Tenant',
            field=models.ManyToManyField(blank=True, related_name='cleaning_schedules', to='users.tenant', verbose_name='Assigned employees'),
        ),
        migrations.AddField(
            model_name='cleaningschedule',
            name='building',
            field=models.ForeignKey(help_text='The building to be cleaned.', on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_schedules', to='properties.building', verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='cleaningschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='cleaningschedule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddIndex(
            model_name='cleaningschedule',
            index=models.Index(fields=['building'], name='cleaning_schedule_building_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningschedule',
            index=models.Index(fields=['scheduled_date'], name='cleaning_schedule_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningschedule',
            index=models.Index(fields=['status'], name='cleaning_schedule_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningschedule',
            index=models.Index(fields=['building', 'scheduled_date'], name='cleaning_building_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='cleaningschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SCHEDULED')), fields=('building', 'scheduled_date'), name='unique_scheduled_cleaning_per_building_date'),
        ),
    ]
