# Generated by Django 6.0.8 on 2026-09-16 09:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('email', models.EmailField(db_index=True, help_text='Email address of the invited person.', max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant'), ('guard', 'Guard'), ('maintenance', 'Maintenance'), ('employee', 'Employee'), ('user', 'User')], db_index=True, help_text='The role being offered to the invited person.', max_length=20, verbose_name='Role')),
                ('invitation_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier (set via signals).', max_length=50, unique=True, verbose_name='Invitation number')),
                ('token_hash', models.CharField(help_text='SHA-256 (or similar) hash of the invitation token.', max_length=128, unique=True, verbose_name='Token hash')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Current status of the invitation.', max_length=20, verbose_name='Status')),
                ('expires_at', models.DateTimeField(help_text='The date and time when the invitation expires.', verbose_name='Expires at')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='The date and time when the invitation was accepted.', null=True, verbose_name='Accepted at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('invited_by', models.ForeignKey(help_text='The user who sent the invitation.', on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invited by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'User invitation',
                'verbose_name_plural': 'User invitations',
                'db_table': 'user_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'status'], name='usr_inv_email_status_idx'), models.Index(fields=['invited_by', 'role'], name='usr_inv_sender_role_idx'), models.Index(fields=['expires_at'], name='usr_inv_expires_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('email', 'invited_by', 'role'), name='unique_pending_invitation_per_sender_role')],
            },
        ),
    ]
