# Generated by Django 6.0.8 on 2026-09-24 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_user_invitation'),
        ('properties', '0008_propertyimage_unit_alter_propertyimage_caption_and_more'),
        ('users', '0005_visitor_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('visit_number', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Visit number')),
                ('visitor_name', models.CharField(max_length=150, verbose_name='Visitor name')),
                ('visitor_phone', models.CharField(blank=True, max_length=32, verbose_name='Visitor phone')),
                ('purpose', models.CharField(blank=True, max_length=255, verbose_name='Purpose')),
                ('expected_arrival', models.DateTimeField(verbose_name='Expected arrival')),
                ('expected_departure', models.DateTimeField(blank=True, null=True, verbose_name='Expected departure')),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected'), ('CHECKED_IN', 'Checked in'), ('CHECKED_OUT', 'Checked out'), ('CANCELLED', 'Cancelled'), ('DENIED', 'Denied')], db_index=True, default='EXPECTED', max_length=20, verbose_name='Status')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Checked in at')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Checked out at')),
                ('check_in_note', models.CharField(blank=True, max_length=255, verbose_name='Check-in note')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitor_visits', to='properties.building', verbose_name='Building')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_visits', to='users.guard', verbose_name='Checked in by')),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_visits', to='users.guard', verbose_name='Checked out by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_visitor_visits', to=settings.AUTH_USER_MODEL, verbose_name='Host')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Visitor visit',
                'verbose_name_plural': 'Visitor visits',
                'db_table': 'visitor_visits',
                'ordering': ['-expected_arrival'],
                'indexes': [models.Index(fields=['building', 'status'], name='visit_building_status_idx'), models.Index(fields=['expected_arrival'], name='visit_expected_arrival_idx'), models.Index(fields=['host', 'expected_arrival'], name='visit_host_arrival_idx')],
            },
        ),
    ]
