# Generated by Django 6.0.8 on 2026-09-25 13:45

from django.db import migrations, models
from django.utils.text import slugify
import uuid


def populate_slugs(apps, schema_editor):
    for model in apps.get_app_config("operations").get_models():
        if not any(field.name == "slug" for field in model._meta.fields):
            continue
        field_names = {field.name for field in model._meta.fields}
        preferred = next((name for name in ("reference_number", "name", "title", "visitor_name", "email") if name in field_names), None)
        for obj in model._base_manager.filter(slug__isnull=True).iterator():
            source = getattr(obj, preferred, None) if preferred else None
            base = slugify(str(source or model._meta.model_name))[:180].strip("-") or model._meta.model_name
            obj.slug = f"{base}-{uuid.uuid4().hex[:8]}"[:200]
            obj.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_visitor_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningschedule',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True, verbose_name='URL slug'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True, verbose_name='URL slug'),
        ),
        migrations.AddField(
            model_name='visitorvisit',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, null=True, unique=True, verbose_name='URL slug'),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
