# Generated by Django 6.0.8 on 2026-08-31 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('request_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the maintenance request.', max_length=50, unique=True, verbose_name='Request number')),
                ('title', models.CharField(help_text='Brief summary of the maintenance issue.', max_length=150, verbose_name='Title')),
                ('description', models.TextField(help_text='Detailed description of the maintenance issue.', verbose_name='Description')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Priority level of the maintenance request.', max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the maintenance request.', max_length=20, verbose_name='Status')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when the request was resolved.', null=True, verbose_name='Resolved at')),
            ],
            options={
                'verbose_name': 'Maintenance request',
                'verbose_name_plural': 'Maintenance requests',
                'db_table': 'maintenance_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('file', models.FileField(upload_to='maintenance/attachments/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('task_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the task.', max_length=50, unique=True, verbose_name='Task number')),
                ('title', models.CharField(help_text='Brief summary of the task.', max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the work to be performed.', verbose_name='Description')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current status of the task.', max_length=20, verbose_name='Status')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Date and time when the task is scheduled to start.', null=True, verbose_name='Scheduled at')),
                ('started_at', models.DateTimeField(blank=True, help_text='Date and time when the task actually started.', null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date and time when the task was completed.', null=True, verbose_name='Completed at')),
            ],
            options={
                'verbose_name': 'Maintenance task',
                'verbose_name_plural': 'Maintenance tasks',
                'db_table': 'maintenance_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
