# Generated by Django 6.0.8 on 2026-08-31 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("users", "0002_invitation_alter_employee_employee_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this record has been soft-deleted.",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated unique identifier for the maintenance request.",
                        max_length=50,
                        unique=True,
                        verbose_name="Request number",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief summary of the maintenance issue.",
                        max_length=150,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the maintenance issue.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        help_text="Priority level of the maintenance request.",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In progress"),
                            ("RESOLVED", "Resolved"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Current status of the maintenance request.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the request was resolved.",
                        null=True,
                        verbose_name="Resolved at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant who submitted the maintenance request.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_requests",
                        to="users.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="The unit where the maintenance issue is located.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_requests",
                        to="properties.unit",
                        verbose_name="Unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance request",
                "verbose_name_plural": "Maintenance requests",
                "db_table": "maintenance_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRequestAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this record has been soft-deleted.",
                        verbose_name="Is deleted",
                    ),
                ),
                ("file", models.FileField(upload_to="maintenance/attachments/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "maintenance_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="maintenance.maintenancerequest",
                        verbose_name="Maintenance request",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this record has been soft-deleted.",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "task_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated unique identifier for the task.",
                        max_length=50,
                        unique=True,
                        verbose_name="Task number",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief summary of the task.",
                        max_length=150,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the work to be performed.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ASSIGNED", "Assigned"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current status of the task.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the task is scheduled to start.",
                        null=True,
                        verbose_name="Scheduled at",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the task actually started.",
                        null=True,
                        verbose_name="Started at",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the task was completed.",
                        null=True,
                        verbose_name="Completed at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "maintenance_agent",
                    models.ForeignKey(
                        help_text="The agent assigned to perform this task.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="users.maintenanceagent",
                        verbose_name="Maintenance agent",
                    ),
                ),
                (
                    "maintenance_request",
                    models.ForeignKey(
                        help_text="The maintenance request this task belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="maintenance.maintenancerequest",
                        verbose_name="Maintenance request",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance task",
                "verbose_name_plural": "Maintenance tasks",
                "db_table": "maintenance_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(fields=["tenant"], name="maintenance_req_tenant_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(fields=["unit"], name="maintenance_req_unit_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(fields=["status"], name="maintenance_req_status_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["priority"], name="maintenance_req_priority_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["maintenance_request"], name="task_request_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["maintenance_agent"], name="task_agent_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="task_status_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["scheduled_at"], name="task_scheduled_idx"),
        ),
    ]
