# Generated by Django 6.0.8 on 2026-08-31 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('maintenance', '0001_initial'),
        ('properties', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant who submitted the maintenance request.', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='users.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='unit',
            field=models.ForeignKey(help_text='The unit where the maintenance issue is located.', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='properties.unit', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='maintenancerequestattachment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='maintenancerequestattachment',
            name='maintenance_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.maintenancerequest', verbose_name='Maintenance request'),
        ),
        migrations.AddField(
            model_name='maintenancerequestattachment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='task',
            name='maintenance_agent',
            field=models.ForeignKey(help_text='The agent assigned to perform this task.', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='users.maintenanceagent', verbose_name='Maintenance agent'),
        ),
        migrations.AddField(
            model_name='task',
            name='maintenance_request',
            field=models.ForeignKey(help_text='The maintenance request this task belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='maintenance.maintenancerequest', verbose_name='Maintenance request'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['tenant'], name='maintenance_req_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['unit'], name='maintenance_req_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['status'], name='maintenance_req_status_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['priority'], name='maintenance_req_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['maintenance_request'], name='task_request_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['maintenance_agent'], name='task_agent_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['scheduled_at'], name='task_scheduled_idx'),
        ),
    ]
