# Generated by Django 6.0.8 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="work_notes",
            field=models.TextField(
                blank=True,
                help_text="Work carried out and useful handover information.",
                verbose_name="Work notes",
            ),
        ),
    ]
