# Generated by Django 6.0.8 on 2026-08-31 10:58

import djmoney.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('charge_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the charge.', max_length=50, unique=True, verbose_name='Charge number')),
                ('charge_type', models.CharField(choices=[('RENT', 'Rent'), ('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('GAS', 'Gas'), ('INTERNET', 'Internet'), ('MAINTENANCE_FEE', 'Maintenance fee'), ('TRASH', 'Trash collection'), ('PARKING', 'Parking'), ('LATE_FEE', 'Late fee'), ('OTHER', 'Other')], help_text='Type of charge (e.g., rent, utilities, maintenance).', max_length=30, verbose_name='Charge type')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('XAF', 'Central African CFA Franc'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='XAF', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='XAF', help_text='Charge amount in the local currency.', max_digits=12, verbose_name='Amount')),
                ('due_date', models.DateField(help_text='Date by which the charge must be paid.', verbose_name='Due date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current payment status of the charge.', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, help_text='Optional details or notes about the charge.', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
                'db_table': 'charges',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('payment_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the payment.', max_length=50, unique=True, verbose_name='Payment number')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('XAF', 'Central African CFA Franc'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='XAF', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='XAF', help_text='Payment amount in the local currency.', max_digits=12, verbose_name='Amount')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank transfer'), ('CREDIT_CARD', 'Credit card'), ('PAYPAL', 'PayPal'), ('CHECK', 'Check'), ('OTHER', 'Other')], help_text='Method used to make the payment (e.g., cash, momo).', max_length=30, verbose_name='Payment method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current payment status.', max_length=20, verbose_name='Status')),
                ('transaction_reference', models.CharField(blank=True, help_text='External reference from the payment gateway.', max_length=100, null=True, unique=True, verbose_name='Transaction reference')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Date and time when the payment was successfully completed.', null=True, verbose_name='Paid at')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment.', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('receipt_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the receipt.', max_length=50, unique=True, verbose_name='Receipt number')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'db_table': 'receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
