# Generated by Django 6.0.8 on 2026-08-31 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='contract',
            field=models.ForeignKey(help_text='The rental contract this charge belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='rentals.rentalcontract', verbose_name='Rental contract'),
        ),
    ]
