# Generated by Django 6.0.8 on 2026-09-23 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_reference',
        ),
        migrations.AddField(
            model_name='payment',
            name='external_reference',
            field=models.CharField(default=django.utils.timezone.now, editable=False, help_text='Unique reference used to identify this payment externally.', max_length=100, unique=True, verbose_name='External reference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='operator',
            field=models.CharField(blank=True, help_text='Mobile money operator used for the payment.', max_length=30, verbose_name='Operator'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, choices=[('CAMPAY', 'CamPay')], help_text='External payment provider used to process the payment.', max_length=30, verbose_name='Payment provider'),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, help_text='External transaction reference returned by the payment gateway.', max_length=100, null=True, unique=True, verbose_name='Transaction reference'),
        ),
    ]
