# Generated by Django 6.0.8 on 2026-09-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_named_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='charge_type',
            field=models.CharField(choices=[('RENT', 'Rent'), ('INITIAL_PAYMENT', 'Initial payment'), ('CONTRACT_EXTENSION', 'Contract extension'), ('ELECTRICITY', 'Electricity'), ('WATER', 'Water'), ('GAS', 'Gas'), ('INTERNET', 'Internet'), ('MAINTENANCE_FEE', 'Maintenance fee'), ('TRASH', 'Trash collection'), ('PARKING', 'Parking'), ('LATE_FEE', 'Late fee'), ('OTHER', 'Other')], help_text='Type of charge (e.g., rent, utilities, maintenance).', max_length=30, verbose_name='Charge type'),
        ),
    ]
