# Generated by Django 6.0.8 on 2026-08-31 14:44

import core.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields
import users.managers
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('email', models.EmailField(help_text='The primary email address used for login and communication.', max_length=254, unique=True, verbose_name='email address')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='International format, e.g. +33123456789.', max_length=128, null=True, region=None, unique=True, validators=[core.validators.validate_phone_number_for_country], verbose_name='phone number')),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Country of residence or origin.', max_length=2, null=True, verbose_name='country')),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload a profile picture (optional).', null=True, upload_to='users/profile/', verbose_name='profile picture')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('SUSPENDED', 'Suspendu')], default='ACTIVE', max_length=20, verbose_name='user status')),
                ('email_verified', models.BooleanField(default=False, help_text='Indicates if the user has confirmed their email address.', verbose_name='email verified')),
                ('phone_verified', models.BooleanField(default=False, help_text='Indicates if the user has confirmed their phone number.', verbose_name='phone verified')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='The IP address used during the last successful login.', null=True, verbose_name='last login IP')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('employee_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the employee.', max_length=50, unique=True, verbose_name='Employee number')),
                ('job_title', models.CharField(blank=True, help_text="The employee's current job title or position.", max_length=150, verbose_name='Job title')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', help_text='Current employment status of the employee.', max_length=20, verbose_name='Status')),
                ('hire_date', models.DateField(blank=True, help_text='The date the employee was hired.', null=True, verbose_name='Hire date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.OneToOneField(help_text='The user account associated with this employee.', on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('guard_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the guard.', max_length=50, unique=True, verbose_name='Guard number')),
                ('shift', models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night'), ('ROTATING', 'Rotating')], default='DAY', help_text="The guard's assigned work shift.", max_length=20, verbose_name='Shift')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.OneToOneField(help_text='The employee record for this security guard.', on_delete=django.db.models.deletion.PROTECT, related_name='guard_profile', to='users.employee', verbose_name='Employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Guard',
                'verbose_name_plural': 'Guards',
                'db_table': 'guards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('landlord_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the landlord.', max_length=50, unique=True, verbose_name='Landlord number')),
                ('verified', models.BooleanField(default=False, help_text="Indicates if the landlord's identity has been verified.", verbose_name='Verified')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.OneToOneField(help_text='The user account associated with this landlord.', on_delete=django.db.models.deletion.PROTECT, related_name='landlord_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Landlord',
                'verbose_name_plural': 'Landlords',
                'db_table': 'landlords',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('email', models.EmailField(help_text='Email address of the invited person.', max_length=254, verbose_name='Email')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for the invitation link.', unique=True, verbose_name='Token')),
                ('role', models.CharField(choices=[('MAINTENANCE', 'Maintenance Agent'), ('GUARD', 'Guard')], help_text='The role being offered: Maintenance Agent or Guard.', max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Current status of the invitation.', max_length=20, verbose_name='Status')),
                ('expires_at', models.DateTimeField(default=users.models.default_invitation_expiration, help_text='The invitation expires after this date.', verbose_name='Expires at')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted.', null=True, verbose_name='Accepted at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.ForeignKey(blank=True, help_text='Existing employee profile if they already have one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='users.employee', verbose_name='Employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(blank=True, help_text='Existing user if they are already registered.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('landlord', models.ForeignKey(help_text='The landlord who sent the invitation.', on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to='users.landlord', verbose_name='Landlord')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'db_table': 'invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('agent_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the maintenance agent.', max_length=50, unique=True, verbose_name='Agent number')),
                ('speciality', models.CharField(blank=True, help_text='Technical speciality of the maintenance agent.', max_length=150, verbose_name='Speciality')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('employee', models.OneToOneField(help_text='The employee record for this maintenance agent.', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_agent_profile', to='users.employee', verbose_name='Employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Maintenance agent',
                'verbose_name_plural': 'Maintenance agents',
                'db_table': 'maintenance_agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('tenant_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the tenant.', max_length=50, unique=True, verbose_name='Tenant number')),
                ('nationality', models.CharField(blank=True, help_text="The tenant's country of nationality.", max_length=100, verbose_name='Nationality')),
                ('occupation', models.CharField(blank=True, help_text="The tenant's current occupation or profession.", max_length=150, verbose_name='Occupation')),
                ('verified', models.BooleanField(default=False, help_text="Indicates if the tenant's identity has been verified.", verbose_name='Verified')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.OneToOneField(help_text='The user account associated with this tenant.', on_delete=django.db.models.deletion.PROTECT, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='user_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='employee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date'], name='employee_hire_date_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status', 'hire_date'], name='employee_status_hire_idx'),
        ),
        migrations.AddIndex(
            model_name='guard',
            index=models.Index(fields=['shift'], name='guard_shift_idx'),
        ),
        migrations.AddIndex(
            model_name='landlord',
            index=models.Index(fields=['verified'], name='landlord_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['token'], name='invitation_token_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['status'], name='invitation_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email', 'status'], name='invitation_email_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['expires_at'], name='invitation_expires_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('email', 'landlord', 'role'), name='unique_pending_invitation_per_landlord_role'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['verified'], name='tenant_verified_idx'),
        ),
    ]
