# Generated by Django 6.0.8 on 2026-08-24 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('landlord_number', models.CharField(max_length=50, unique=True)),
                ('total_properties', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'landlords',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['verified'], name='landlord_verified_idx')],
            },
        ),
    ]
