# Generated by Django 6.0.8 on 2026-09-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_landlord',
            field=models.BooleanField(default=False, help_text='Indicates if the user is a landlord.', verbose_name='is landlord'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tenant',
            field=models.BooleanField(default=False, help_text='Indicates if the user is a tenant.', verbose_name='is tenant'),
        ),
    ]
