# Generated by Django 6.0.8 on 2026-08-31 10:23

import core.validators
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this record has been soft-deleted.",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the invited person.",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token for the invitation link.",
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MAINTENANCE", "Maintenance Agent"),
                            ("GUARD", "Guard"),
                        ],
                        help_text="The role being offered: Maintenance Agent or Guard.",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("EXPIRED", "Expired"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Current status of the invitation.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=users.models.default_invitation_expiration,
                        help_text="The invitation expires after this date.",
                        verbose_name="Expires at",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the invitation was accepted.",
                        null=True,
                        verbose_name="Accepted at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitations",
                "db_table": "invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto-generated unique identifier for the employee.",
                max_length=50,
                unique=True,
                verbose_name="Employee number",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(
                blank=True,
                help_text="The date the employee was hired.",
                null=True,
                verbose_name="Hire date",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="job_title",
            field=models.CharField(
                blank=True,
                help_text="The employee's current job title or position.",
                max_length=150,
                verbose_name="Job title",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("SUSPENDED", "Suspended"),
                ],
                default="ACTIVE",
                help_text="Current employment status of the employee.",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                help_text="The user account associated with this employee.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="guard",
            name="employee",
            field=models.OneToOneField(
                help_text="The employee record for this security guard.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guard_profile",
                to="users.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="guard",
            name="guard_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto-generated unique identifier for the guard.",
                max_length=50,
                unique=True,
                verbose_name="Guard number",
            ),
        ),
        migrations.AlterField(
            model_name="guard",
            name="shift",
            field=models.CharField(
                choices=[("DAY", "Day"), ("NIGHT", "Night"), ("ROTATING", "Rotating")],
                default="DAY",
                help_text="The guard's assigned work shift.",
                max_length=20,
                verbose_name="Shift",
            ),
        ),
        migrations.AlterField(
            model_name="landlord",
            name="landlord_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto-generated unique identifier for the landlord.",
                max_length=50,
                unique=True,
                verbose_name="Landlord number",
            ),
        ),
        migrations.AlterField(
            model_name="landlord",
            name="user",
            field=models.OneToOneField(
                help_text="The user account associated with this landlord.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="landlord_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="landlord",
            name="verified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the landlord's identity has been verified.",
                verbose_name="Verified",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceagent",
            name="agent_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto-generated unique identifier for the maintenance agent.",
                max_length=50,
                unique=True,
                verbose_name="Agent number",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceagent",
            name="employee",
            field=models.OneToOneField(
                help_text="The employee record for this maintenance agent.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_agent_profile",
                to="users.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="nationality",
            field=models.CharField(
                blank=True,
                help_text="The tenant's country of nationality.",
                max_length=100,
                verbose_name="Nationality",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="occupation",
            field=models.CharField(
                blank=True,
                help_text="The tenant's current occupation or profession.",
                max_length=150,
                verbose_name="Occupation",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto-generated unique identifier for the tenant.",
                max_length=50,
                unique=True,
                verbose_name="Tenant number",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="user",
            field=models.OneToOneField(
                help_text="The user account associated with this tenant.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenant_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="verified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the tenant's identity has been verified.",
                verbose_name="Verified",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Country of residence or origin.",
                max_length=2,
                null=True,
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="The primary email address used for login and communication.",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user has confirmed their email address.",
                verbose_name="email verified",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="The IP address used during the last successful login.",
                null=True,
                verbose_name="last login IP",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="International format, e.g. +33123456789.",
                max_length=128,
                null=True,
                region=None,
                unique=True,
                validators=[core.validators.validate_phone_number_for_country],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user has confirmed their phone number.",
                verbose_name="phone verified",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile picture (optional).",
                null=True,
                upload_to="users/profile/",
                verbose_name="profile picture",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Actif"),
                    ("INACTIVE", "Inactif"),
                    ("SUSPENDED", "Suspendu"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="user status",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["status", "hire_date"], name="employee_status_hire_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guard",
            index=models.Index(fields=["shift"], name="guard_shift_idx"),
        ),
        migrations.AddIndex(
            model_name="landlord",
            index=models.Index(fields=["verified"], name="landlord_verified_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["verified"], name="tenant_verified_idx"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Existing employee profile if they already have one.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitations",
                to="users.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="landlord",
            field=models.ForeignKey(
                help_text="The landlord who sent the invitation.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_invitations",
                to="users.landlord",
                verbose_name="Landlord",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Existing user if they are already registered.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["token"], name="invitation_token_idx"),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["status"], name="invitation_status_idx"),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["email", "status"], name="invitation_email_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["expires_at"], name="invitation_expires_at_idx"),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("email", "landlord", "role"),
                name="unique_pending_invitation_per_landlord_role",
            ),
        ),
    ]
