# Generated by Django 6.0.8 on 2026-09-07 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_landlord_user_is_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(help_text='The user account associated with this employee.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='guard',
            name='employee',
            field=models.OneToOneField(help_text='The employee record for this security guard.', on_delete=django.db.models.deletion.CASCADE, related_name='guard_profile', to='users.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='user',
            field=models.OneToOneField(help_text='The user account associated with this landlord.', on_delete=django.db.models.deletion.CASCADE, related_name='landlord_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='maintenanceagent',
            name='employee',
            field=models.OneToOneField(help_text='The employee record for this maintenance agent.', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_agent_profile', to='users.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(help_text='The user account associated with this tenant.', on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
