# Generated by Django 6.0.8 on 2026-08-25 00:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_landlord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
    ]
