# Generated by Django 6.0.8 on 2026-09-02 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.AlterField(
            model_name='otp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='The number of verification attempts made with this OTP.', verbose_name='attempts'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code_hash',
            field=models.CharField(help_text='Hashed representation of the OTP code.', max_length=128, verbose_name='code hash'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiration_at',
            field=models.DateTimeField(help_text='The date and time after which this OTP is no longer valid.', verbose_name='expires at'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Whether this OTP has been used for verification.', verbose_name='used'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('signup', 'Sign up'), ('login', 'Sign in'), ('password_reset', 'Password reset')], help_text='The purpose for which this OTP was generated.', max_length=32, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(help_text='The user associated with this OTP.', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
