# Generated by Django 6.0.8 on 2026-08-25 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('SUSPENDED', 'Suspendu')], default='ACTIVE', max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='employee_status_idx'), models.Index(fields=['hire_date'], name='employee_hire_date_idx')],
            },
        ),
    ]
