# Generated by Django 6.0.8 on 2026-08-25 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guard_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('shift', models.CharField(choices=[('DAY', 'Jour'), ('NIGHT', 'Nuit'), ('ROTATING', 'Rotation')], default='DAY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guard_profile', to='users.employee')),
            ],
            options={
                'db_table': 'guards',
                'ordering': ['-created_at'],
            },
        ),
    ]
