# Generated by Django 6.0.8 on 2026-09-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_maintenanceagent_landlords'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='landlords',
            field=models.ManyToManyField(blank=True, help_text='Landlords whose residences this guard can secure.', related_name='guards', to='users.landlord', verbose_name='Landlords'),
        ),
    ]
