# Generated by Django 6.0.8 on 2026-08-25 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_guard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('speciality', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_agent_profile', to='users.employee')),
            ],
            options={
                'db_table': 'maintenance_agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
