# Generated by Django 6.0.8 on 2026-08-27 08:37

import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('property_number', models.CharField(editable=False, help_text='Auto-generated unique identifier for the property.', max_length=50, unique=True, verbose_name='Property number')),
                ('name', models.CharField(help_text="The official name of the property (e.g., 'Sunset Tower').", max_length=150, verbose_name='Property name')),
                ('description', models.TextField(blank=True, help_text='Additional details about the property, such as amenities or history.', verbose_name='Description')),
                ('address', models.CharField(help_text="Street address of the property (e.g., '123 Main St').", max_length=255, verbose_name='Address')),
                ('city', models.CharField(help_text='City where the property is located.', max_length=100, verbose_name='City')),
                ('country', django_countries.fields.CountryField(help_text='Country where the property is located.', max_length=2, verbose_name='Country')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_CONSTRUCTION', 'Under construction')], db_index=True, default='ACTIVE', help_text='Current operational status of the property.', max_length=30, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
