# Generated by Django 6.0.8 on 2026-09-03 14:53

import core.validators
import django_countries.fields
import djmoney.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('building_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the building.', max_length=50, unique=True, verbose_name='Building number')),
                ('name', models.CharField(help_text="The official name of the building (e.g., 'Tower A').", max_length=150, verbose_name='Building name')),
                ('description', models.TextField(blank=True, help_text='Additional details about the building, such as amenities or construction year.', verbose_name='Description')),
                ('floors', models.PositiveIntegerField(default=1, help_text='Total number of floors in the building.', verbose_name='Number of floors')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_CONSTRUCTION', 'Under construction')], default='ACTIVE', help_text='Current operational status of the building.', max_length=30, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'db_table': 'buildings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('property_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the property.', max_length=50, unique=True, verbose_name='Property number')),
                ('name', models.CharField(help_text="The official name of the property (e.g., 'Sunset Tower').", max_length=150, verbose_name='Property name')),
                ('description', models.TextField(blank=True, help_text='Additional details about the property, such as amenities or history.', verbose_name='Description')),
                ('address', models.CharField(help_text="Street address of the property (e.g., '123 Main St').", max_length=255, verbose_name='Address')),
                ('city', models.CharField(help_text='City where the property is located.', max_length=100, verbose_name='City')),
                ('country', django_countries.fields.CountryField(help_text='Country where the property is located.', max_length=2, verbose_name='Country')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_CONSTRUCTION', 'Under construction')], default='ACTIVE', help_text='Current operational status of the property.', max_length=30, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('image', models.ImageField(help_text='Upload a JPG, PNG, or WebP image. Recommended size: 1920*1080 pixels, max 5MB.', upload_to='properties/images/', validators=[core.validators.validate_image_size, core.validators.validate_image_extension], verbose_name='Image')),
                ('caption', models.CharField(default='Property Image', help_text='Setup caption caption of Property Image.', verbose_name='Property Image')),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Mark this image as the main/cover image for the property. Only one image per property should be primary.', verbose_name='Primary image')),
            ],
            options={
                'verbose_name': 'Property image',
                'verbose_name_plural': 'Property images',
                'db_table': 'property_images',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('unit_number', models.CharField(help_text='Unique unit identifier within the building. Must be unique per building (enforced by a database constraint).', max_length=50, verbose_name='Unit number')),
                ('floor', models.PositiveIntegerField(default=0, help_text='Floor number where the unit is located (0 = ground floor).', verbose_name='Floor')),
                ('unit_type', models.CharField(choices=[('STUDIO', 'Studio'), ('APARTMENT', 'Apartment'), ('OFFICE', 'Office'), ('RETAIL', 'Retail'), ('WAREHOUSE', 'Warehouse'), ('PENTHOUSE', 'Penthouse')], default='APARTMENT', help_text='Category of the unit (e.g., studio, apartment, office).', max_length=50, verbose_name='Unit type')),
                ('bedrooms', models.PositiveIntegerField(default=0, help_text='Number of bedrooms in the unit.', verbose_name='Bedrooms')),
                ('bathrooms', models.PositiveIntegerField(default=1, help_text='Number of bathrooms in the unit.', verbose_name='Bathrooms')),
                ('area', models.DecimalField(blank=True, decimal_places=2, help_text='Total area of the unit in square meters.', max_digits=10, null=True, verbose_name='Area')),
                ('monthly_rent_currency', djmoney.models.fields.CurrencyField(choices=[('XAF', 'Central African CFA Franc'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='XAF', editable=False, max_length=3)),
                ('monthly_rent', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='XAF', help_text='Monthly rental price in the local currency.', max_digits=12, verbose_name='Monthly rent')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('MAINTENANCE', 'Under maintenance'), ('INACTIVE', 'Inactive')], default='AVAILABLE', help_text='Current occupancy status of the unit.', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'units',
                'ordering': ['building', 'unit_number'],
            },
        ),
    ]
