# Generated by Django 6.0.8 on 2026-08-31 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('properties', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='building',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='property',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(help_text='The landlord who owns this property.', on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='users.landlord', verbose_name='Landlord'),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='building',
            name='property_ref',
            field=models.ForeignKey(help_text='The property that this building belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='properties.property', verbose_name='property'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(help_text='The property this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='unit',
            name='building',
            field=models.ForeignKey(help_text='The building that contains this unit.', on_delete=django.db.models.deletion.PROTECT, related_name='units', to='properties.building', verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['landlord'], name='property_landlord_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='property_status_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='property_city_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['property_ref'], name='building_property_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['status'], name='building_status_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property'], name='property_image_property_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property', 'is_primary'], name='property_image_primary_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['building'], name='unit_building_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status'], name='unit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['floor'], name='unit_floor_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_type'], name='unit_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('building', 'unit_number'), name='unique_unit_number_per_building'),
        ),
    ]
