# Generated by Django 6.0.8 on 2026-09-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('MIXED', 'Mixed use')], default='RESIDENTIAL', help_text='The type of the property (e.g., Residential, Commercial).', max_length=30, verbose_name='Property type'),
        ),
    ]
