# Generated by Django 6.0.8 on 2026-09-12 14:44

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0014_alter_city_search_names'),
        ('properties', '0003_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='region', chained_model_field='region', help_text='City where the property is located.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country where the property is located.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country', verbose_name='Country'),
        ),
    ]
