# Generated by Django 6.0.8 on 2026-09-12 14:51

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0014_alter_city_search_names'),
        ('properties', '0004_alter_property_city_alter_property_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region'),
        ),
    ]
