# Generated by Django 6.0.8 on 2026-09-12 16:16

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0014_alter_city_search_names'),
        ('properties', '0005_property_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='region',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', help_text='Region where the property is located.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region', verbose_name='Region'),
        ),
    ]
