# Generated by Django 6.0.8 on 2026-09-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='default_currency',
            field=models.CharField(choices=[('XAF', 'XAF — CFA Franc'), ('EUR', 'EUR — Euro'), ('USD', 'USD — US Dollar')], default='XAF', help_text='Default currency used for rent and charges in this property.', max_length=3, verbose_name='Default currency'),
        ),
        migrations.AddField(
            model_name='property',
            name='default_monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suggested monthly rent amount for new units in this property.', max_digits=12, null=True, verbose_name='Default monthly rent'),
        ),
        migrations.AddField(
            model_name='property',
            name='maintenance_management_enabled',
            field=models.BooleanField(default=True, help_text='Allow maintenance requests to be associated with this property.', verbose_name='Maintenance management'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenant_management_enabled',
            field=models.BooleanField(default=True, help_text='Allow ROOMRUN to manage tenants and rental contracts for this property.', verbose_name='Tenant management'),
        ),
    ]
