# Generated by Django 6.0.8 on 2026-09-14 11:48

import core.validators
import django.db.models.deletion
import utils.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_default_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='The unit this image belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(default='Property Image', help_text='A short description of the image.', max_length=255, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(help_text='Upload a JPG, PNG, or WebP image. Recommended size: 1920*1080 pixels, max 5MB.', upload_to=utils.helpers.property_image_upload_path, validators=[core.validators.validate_image_size, core.validators.validate_image_extension], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Mark this image as the main/cover image for the property. Only one image per property should be primary.', verbose_name='Primary image'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(blank=True, help_text='The property this image belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Property'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['unit'], name='property_image_unit_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['unit', 'is_primary'], name='unit_image_primary_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyimage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('property__isnull', False), ('unit__isnull', True)), models.Q(('property__isnull', True), ('unit__isnull', False)), _connector='OR'), name='image_exactly_one_owner'),
        ),
    ]
