# Generated by Django 6.0.8 on 2026-09-03 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('announcement_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the announcement.', max_length=50, unique=True, verbose_name='Announcement number')),
                ('title', models.CharField(help_text='The headline of the announcement.', max_length=200, verbose_name='Title')),
                ('content', models.TextField(help_text='The full content of the announcement.', verbose_name='Content')),
                ('published_at', models.DateTimeField(blank=True, help_text='The date and time when the announcement was published.', null=True, verbose_name='Published at')),
                ('expires_at', models.DateTimeField(blank=True, help_text='The date and time when the announcement will expire.', null=True, verbose_name='Expires at')),
                ('status', models.CharField(choices=[('ARCHIVED', 'Archived'), ('EXPIRED', 'Expired'), ('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', help_text='Current status of the announcement.', max_length=20, verbose_name='Status')),
                ('target', models.CharField(choices=[('ALL_TENANTS', 'All tenants'), ('BUILDING', 'Building'), ('UNIT', 'Unit')], default='ALL_TENANTS', help_text='The intended audience for this announcement.', max_length=20, verbose_name='Target')),
                ('attachment_url', models.URLField(blank=True, help_text='Optional URL to an external attachment (e.g., PDF, image).', verbose_name='Attachment URL')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read at')),
                ('message_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the message.', max_length=50, unique=True, verbose_name='Message number')),
                ('content', models.TextField(help_text='The actual content of the message.', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates whether this record has been soft-deleted.', verbose_name='Is deleted')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read at')),
                ('notification_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique identifier for the notification.', max_length=50, unique=True, verbose_name='Notification number')),
                ('title', models.CharField(help_text='Short headline of the notification.', max_length=200, verbose_name='Title')),
                ('message', models.TextField(help_text='The full content of the notification.', verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('RENT_REMINDER', 'Rent reminder'), ('MAINTENANCE', 'Maintenance'), ('TASK', 'Task'), ('ANNOUNCEMENT', 'Announcement'), ('SYSTEM', 'System')], help_text='The category of this notification.', max_length=30, verbose_name='Notification type')),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
