# Generated by Django 6.0.8 on 2026-08-31 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("properties", "0001_initial"),
        ("users", "0002_invitation_alter_employee_employee_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this record has been soft-deleted.",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "announcement_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated unique identifier for the announcement.",
                        max_length=50,
                        unique=True,
                        verbose_name="Announcement number",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The headline of the announcement.",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The full content of the announcement.",
                        verbose_name="Content",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when the announcement was published.",
                        null=True,
                        verbose_name="Published at",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when the announcement will expire.",
                        null=True,
                        verbose_name="Expires at",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ARCHIVED", "Archived"),
                            ("EXPIRED", "Expired"),
                            ("DRAFT", "Draft"),
                            ("SCHEDULED", "Scheduled"),
                            ("PUBLISHED", "Published"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Current status of the announcement.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("ALL_TENANTS", "All tenants"),
                            ("BUILDING", "Building"),
                            ("UNIT", "Unit"),
                        ],
                        default="ALL_TENANTS",
                        help_text="The intended audience for this announcement.",
                        max_length=20,
                        verbose_name="Target",
                    ),
                ),
                (
                    "attachment_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL to an external attachment (e.g., PDF, image).",
                        verbose_name="Attachment URL",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements",
                        to="properties.building",
                        verbose_name="Building",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "landlord",
                    models.ForeignKey(
                        help_text="The landlord who published this announcement.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements",
                        to="users.landlord",
                        verbose_name="Landlord",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements",
                        to="properties.unit",
                        verbose_name="Unit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "db_table": "announcements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["landlord"], name="announcement_landlord_idx"),
                    models.Index(fields=["status"], name="announcement_status_idx"),
                    models.Index(fields=["target"], name="announcement_target_idx"),
                    models.Index(
                        fields=["published_at"], name="announcement_published_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="announcement_expires_idx"
                    ),
                    models.Index(
                        fields=["status", "published_at"],
                        name="ann_status_published_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this record has been soft-deleted.",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Read"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read at"),
                ),
                (
                    "message_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated unique identifier for the message.",
                        max_length=50,
                        unique=True,
                        verbose_name="Message number",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The actual content of the message.",
                        verbose_name="Content",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="communications.message",
                        verbose_name="Reply to",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The user who received the message.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="The user who sent the message.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["sender"], name="message_sender_idx"),
                    models.Index(fields=["recipient"], name="message_recipient_idx"),
                    models.Index(fields=["is_read"], name="message_read_idx"),
                    models.Index(fields=["created_at"], name="message_created_at_idx"),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="message_recipient_read_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indicates whether this record has been soft-deleted.",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Read"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read at"),
                ),
                (
                    "notification_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated unique identifier for the notification.",
                        max_length=50,
                        unique=True,
                        verbose_name="Notification number",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short headline of the notification.",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The full content of the notification.",
                        verbose_name="Message",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "Payment"),
                            ("RENT_REMINDER", "Rent reminder"),
                            ("MAINTENANCE", "Maintenance"),
                            ("TASK", "Task"),
                            ("ANNOUNCEMENT", "Announcement"),
                            ("SYSTEM", "System"),
                        ],
                        help_text="The category of this notification.",
                        max_length=30,
                        verbose_name="Notification type",
                    ),
                ),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The user who receives this notification.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_contexts",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient"], name="notification_recipient_idx"
                    ),
                    models.Index(fields=["is_read"], name="notification_read_idx"),
                    models.Index(
                        fields=["notification_type"], name="notification_type_idx"
                    ),
                ],
            },
        ),
    ]
