# Generated by Django 6.0.8 on 2026-09-22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0003_create_missing_chat_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="direct_key",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unique key for a two-person conversation.",
                max_length=73,
                null=True,
                unique=True,
                verbose_name="Direct conversation key",
            ),
        ),
    ]
