# Generated by Django 6.0.8 on 2026-09-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_conversation_direct_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('RENT_REMINDER', 'Rent reminder'), ('MAINTENANCE', 'Maintenance'), ('TASK', 'Task'), ('MESSAGE', 'Message'), ('ANNOUNCEMENT', 'Announcement'), ('SYSTEM', 'System')], help_text='The category of this notification.', max_length=30, verbose_name='Notification type'),
        ),
    ]
